### ISSUE TITLE
Implementation Issue

### ISSUE THREAD

**Issue by daviek19** [TIBCOSoftware/bw-samples#7]
**Description**
Hello. I have tried following the instructions step by step. The configuration replacing is happening but then the container is not starting up. I run into the following error:

**Error Log Dump**
BW_PROFILE is set to 'SIT.substvar'
******* Custom BWCE Config *******
Key: TIBCODB
replacing at: TIBCODB

******* End Custom BWCE Config *******

`BW_PROFILE is set to 'SIT.substvar'
******* Custom BWCE Config *******
Key: TIBCODB
replacing at: TIBCODB

******* End Custom BWCE Config *******

TIBCO BusinessWorks Container Edition version 2.4.4, build V34, 2019-05-22                                                 14:02:40.837 INFO
[main] com.tibco.thor.frwk - bwappnode TIBCO BusinessWorks Container Edition version 2.4.4, build V34, 2019-05-22 initialized using logging config /tmp/tibco.home/bwce/2.4/config/logback.xml
-------------------------------------------
  Starting AppNode framework
-------------------------------------------
!SESSION 2019-06-20 14:02:49.028 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_192
java.vendor=Oracle Corporation                                                                                             BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US

!ENTRY com.tibco.neo.eclipse.support.osgi 4 0 2019-06-20 14:02:49.032
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in com.tibco.neo.component.osgi.NeoOSGiBundleActivator.start() of bundle com.tibco.neo.eclipse.support.osgi.
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:792)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
        at org.eclipse.osgi.container.Module.doStart(Module.java:571)
        at org.eclipse.osgi.container.Module.start(Module.java:439)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
        at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
        at org.eclipse.osgi.container.Module.doStart(Module.java:571)
        at org.eclipse.osgi.container.Module.start(Module.java:439)
        at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:412)
        at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
        at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.start(StartLocalCommand.java:480)
        at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.doExecute(StartLocalCommand.java:180)
        at com.tibco.bw.thor.management.cli.commands.AbstractCommand.execute(AbstractCommand.java:62)
        at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35)
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:474)
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:400)
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)                                                                   at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)                                                         at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
        at com.tibco.bw.thor.management.cli.commands.AbstractMain.run(AbstractMain.java:482)
        at com.tibco.bw.thor.management.cli.commands.AbstractMain.run(AbstractMain.java:451)
        at com.tibco.bw.thor.management.cli.commands.AbstractMain.mainLoop(AbstractMain.java:179)
        at com.tibco.bw.thor.admin.node.Main.main(Main.java:36)
Caused by: java.lang.IllegalArgumentException: TIBCO-AMX-INFRA-002000: invalid null value                                          at com.tibco.neo.model.types.ComponentID.<init>(ComponentID.java:31)
        at com.tibco.neo.component.osgi.BundleMapKey.<init>(BundleMapKey.java:27)
        at com.tibco.neo.component.osgi.OSGiEMFPackageRegistryManager.init(OSGiEMFPackageRegistryManager.java:139)
        at com.tibco.neo.component.osgi.NeoOSGiBundleActivator.start(NeoOSGiBundleActivator.java:67)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
        ... 29 more
Root exception:
java.lang.IllegalArgumentException: TIBCO-AMX-INFRA-002000: invalid null value
        at com.tibco.neo.model.types.ComponentID.<init>(ComponentID.java:31)
        at com.tibco.neo.component.osgi.BundleMapKey.<init>(BundleMapKey.java:27)
        at com.tibco.neo.component.osgi.OSGiEMFPackageRegistryManager.init(OSGiEMFPackageRegistryManager.java:139)                 at com.tibco.neo.component.osgi.NeoOSGiBundleActivator.start(NeoOSGiBundleActivator.java:67)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
        at org.eclipse.osgi.container.Module.doStart(Module.java:571)
        at org.eclipse.osgi.container.Module.start(Module.java:439)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
        at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
        at org.eclipse.osgi.container.Module.doStart(Module.java:571)
        at org.eclipse.osgi.container.Module.start(Module.java:439)
        at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:412)
        at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
        at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.start(StartLocalCommand.java:480)
        at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.doExecute(StartLocalCommand.java:180)
        at com.tibco.bw.thor.management.cli.commands.AbstractCommand.execute(AbstractCommand.java:62)
        at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35)
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:474)
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:400)
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
        at com.tibco.bw.thor.management.cli.commands.AbstractMain.run(AbstractMain.java:482)
        at com.tibco.bw.thor.management.cli.commands.AbstractMain.run(AbstractMain.java:451)
        at com.tibco.bw.thor.management.cli.commands.AbstractMain.mainLoop(AbstractMain.java:179)
        at com.tibco.bw.thor.admin.node.Main.main(Main.java:36)

!ENTRY org.eclipse.osgi 4 0 2019-06-20 14:02:50.157
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.ServiceException: Exception in com.tibco.bw.thor.management.equinox.hook.BW6ProductEventHook.event()
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHookPrivileged(ServiceRegistry.java:1288)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHooksPrivileged(ServiceRegistry.java:1263)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.notifyEventHooksPrivileged(EquinoxEventPublisher.java:186)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:146)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:75)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:67)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:102)        at org.eclipse.osgi.container.Module.publishEvent(Module.java:466)
        at org.eclipse.osgi.container.Module.doStart(Module.java:568)
        at org.eclipse.osgi.container.Module.start(Module.java:439)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
        at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
        at org.eclipse.osgi.container.Module.doStart(Module.java:571)
        at org.eclipse.osgi.container.Module.start(Module.java:439)
        at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:412)
        at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
        at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.start(StartLocalCommand.java:480)
        at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.doExecute(StartLocalCommand.java:180)
        at com.tibco.bw.thor.management.cli.commands.AbstractCommand.execute(AbstractCommand.java:62)
        at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35)
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:474)
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:400)
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
        at com.tibco.bw.thor.management.cli.commands.AbstractMain.run(AbstractMain.java:482)
        at com.tibco.bw.thor.management.cli.commands.AbstractMain.run(AbstractMain.java:451)
        at com.tibco.bw.thor.management.cli.commands.AbstractMain.mainLoop(AbstractMain.java:179)
        at com.tibco.bw.thor.admin.node.Main.main(Main.java:36)
Caused by: java.lang.NullPointerException
        at com.tibco.bw.thor.management.equinox.hook.BW6ProductEventHook.event(BW6ProductEventHook.java:47)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$2.call(EquinoxEventPublisher.java:189)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHookPrivileged(ServiceRegistry.java:1280)
        ... 33 more

!ENTRY org.eclipse.osgi 4 0 2019-06-20 14:02:50.196
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.ServiceException: Exception in com.tibco.bw.thor.management.equinox.hook.BW6ProductEventHook.event()
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHookPrivileged(ServiceRegistry.java:1288)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHooksPrivileged(ServiceRegistry.java:1263)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.notifyEventHooksPrivileged(EquinoxEventPublisher.java:186)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:146)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:75)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:67)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:102)        at org.eclipse.osgi.container.Module.publishEvent(Module.java:466)
        at org.eclipse.osgi.container.Module.start(Module.java:457)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
        at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
        at org.eclipse.osgi.container.Module.doStart(Module.java:571)
        at org.eclipse.osgi.container.Module.start(Module.java:439)
        at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:393)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:412)
        at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
        at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.start(StartLocalCommand.java:480)
        at com.tibco.bw.thor.admin.node.commands.StartLocalCommand.doExecute(StartLocalCommand.java:180)
        at com.tibco.bw.thor.management.cli.commands.AbstractCommand.execute(AbstractCommand.java:62)
        at org.apache.felix.gogo.commands.basic.AbstractCommand.execute(AbstractCommand.java:35)
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:474)
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:400)
        at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
        at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
        at com.tibco.bw.thor.management.cli.commands.AbstractMain.run(AbstractMain.java:482)
        at com.tibco.bw.thor.management.cli.commands.AbstractMain.run(AbstractMain.java:451)
        at com.tibco.bw.thor.management.cli.commands.AbstractMain.mainLoop(AbstractMain.java:179)
        at com.tibco.bw.thor.admin.node.Main.main(Main.java:36)
Caused by: java.lang.NullPointerException
        at com.tibco.bw.thor.management.equinox.hook.BW6ProductEventHook.event(BW6ProductEventHook.java:47)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher$2.call(EquinoxEventPublisher.java:189)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.notifyHookPrivileged(ServiceRegistry.java:1280)
        ... 32 more
14:02:56.546 INFO  [main] com.tibco.bw.frwk.engine.BWEngine - TIBCO-BW-FRWK-300002: BW Engine [Main] started successfully.
14:02:57.077 INFO  [main] com.tibco.thor.frwk - AppNode (OSGi Framework) started in 9 seconds
-------------------------------------------
AppNode (OSGi Framework) started in 9 seconds
-------------------------------------------
14:02:57.083 INFO  [Framework Event Dispatcher: Equinox Container: 70f84712-6493-0019-1880-fcc39e1844e8] com.tibco.thor.frwk.Deployer - TIBCO-THOR-FRWK-300001: Started OSGi Framework of AppNode [standalone] in AppSpace [standalone] of Domain [standalone]
14:03:05.117 ERROR [Framework Event Dispatcher: Equinox Container: 70f84712-6493-0019-1880-fcc39e1844e8] com.tibco.thor.frwk.Deployer - Failed to create deployment unit handler, TIBCO-THOR-FRWK-600054: Invalid TIBCO.xml file..
   <CausedBy> org.eclipse.emf.ecore.resource.Resource$IOWrappedException: Package with uri 'http://schemas.tibco.com/tra/model/core/PackagingModel' not found. (bundleresource://445.fwk1789282489/META-INF/TIBCO.xml, 2, 142).
   <CausedBy> org.eclipse.emf.ecore.xmi.PackageNotFoundException: Package with uri 'http://schemas.tibco.com/tra/model/core/PackagingModel' not found. (bundleresource://445.fwk1789282489/META-INF/TIBCO.xml, 2, 142)

com.tibco.neo.exception.BaseException: TIBCO-THOR-FRWK-600054: Invalid TIBCO.xml file.
        at com.tibco.bw.thor.runtime.ApplicationHandler.parseTIBCOFile(ApplicationHandler.java:1357) ~[bundleFile:na]
        at com.tibco.bw.thor.runtime.ApplicationHandler.createApplication(ApplicationHandler.java:1155) ~[bundleFile:na]
        at com.tibco.bw.thor.runtime.ApplicationHandler.init(ApplicationHandler.java:1486) ~[bundleFile:na]
        at com.tibco.bw.thor.runtime.Deployer.addingBundle(Deployer.java:484) [bundleFile:na]
        at com.tibco.bw.thor.runtime.Deployer.addingBundle(Deployer.java:1) [bundleFile:na]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:469) [org.eclipse.osgi_3.10.1.v20140909-1633.jar:na]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1) [org.eclipse.osgi_3.10.1.v20140909-1633.jar:na]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.eclipse.osgi_3.10.1.v20140909-1633.jar:na]
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183) [org.eclipse.osgi_3.10.1.v20140909-1633.jar:na]
        at org.osgi.util.tracker.BundleTracker.open(BundleTracker.java:156) [org.eclipse.osgi_3.10.1.v20140909-1633.jar:na]        at com.tibco.bw.thor.runtime.Deployer$1.frameworkEvent(Deployer.java:303) [bundleFile:na]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:926) [org.eclipse.osgi_3.10.1.v20140909-1633.jar:na]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi_3.10.1.v20140909-1633.jar:na]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi_3.10.1.v20140909-1633.jar:na]
Caused by: org.eclipse.emf.ecore.resource.Resource$IOWrappedException: Package with uri 'http://schemas.tibco.com/tra/model/core/PackagingModel' not found. (bundleresource://445.fwk1789282489/META-INF/TIBCO.xml, 2, 142)
        at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.handleErrors(XMLLoadImpl.java:77) ~[org.eclipse.emf.ecore.xmi_2.10.1.v20140901-1043.jar:na]
        at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:185) ~[org.eclipse.emf.ecore.xmi_2.10.1.v20140901-1043.jar:na]
        at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:261) ~[org.eclipse.emf.ecore.xmi_2.10.1.v20140901-1043.jar:na]
        at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1518) ~[org.eclipse.emf.ecore_2.10.1.v20140901-1043.jar:na]

        at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1297) ~[org.eclipse.emf.ecore_2.10.1.v20140901-1043.jar:na]

        at com.tibco.bw.thor.runtime.ApplicationHandler.parseTIBCOFile(ApplicationHandler.java:1294) ~[bundleFile:na]
        ... 13 common frames omitted                                                                                       Caused by: org.eclipse.emf.ecore.xmi.PackageNotFoundException: Package with uri 'http://schemas.tibco.com/tra/model/core/PackagingModel' not found. (bundleresource://445.fwk1789282489/META-INF/TIBCO.xml, 2, 142)
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.getPackageForURI(XMLHandler.java:2625) ~[org.eclipse.emf.ecore.xmi_2.10.1.v20140901-1043.jar:na]
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.getFactoryForPrefix(XMLHandler.java:2458) ~[org.eclipse.emf.ecore.xmi_2.10.1.v20140901-1043.jar:na]
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createObjectByType(XMLHandler.java:1335) ~[org.eclipse.emf.ecore.xmi_2.10.1.v20140901-1043.jar:na]
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createTopObject(XMLHandler.java:1504) ~[org.eclipse.emf.ecore.xmi_2.10.1.v20140901-1043.jar:na]
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.processElement(XMLHandler.java:1026) ~[org.eclipse.emf.ecore.xmi_2.10.1.v20140901-1043.jar:na]
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:1008) ~[org.eclipse.emf.ecore.xmi_2.10.1.v20140901-1043.jar:na]
        at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:719) ~[org.eclipse.emf.ecore.xmi_2.10.1.v20140901-1043.jar:na]
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source) ~[xercesImpl.jar:na]                           at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl.jar:na]             at org.apache.xerces.impl.XMLDocumentScannerImpl$ContentDispatcher.scanRootElementHook(Unknown Source) ~[xercesImpl.jar:na]
                                                                                             at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl.jar:na]
                                                       at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl.jar:na]                                 at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl.jar:na]                                          at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl.jar:na]
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl.jar:na]                           at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source) ~[xercesImpl.jar:na]
        at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175) ~[org.eclipse.emf.ecore.xmi_2.10.1.v20140901-1043.jar:na]
        ... 17 common frames omitted`

**Comment by adriel3005** [comment]
@daviek19 Did you find a solution to this? I am running into the same error.

**Comment by daviek19** [comment]
> [adriel3005](/adriel3005)

Unfortunately I did not find a solution.
